### ISSUE TITLE
Third Bar

### ISSUE THREAD

**Issue by Memorize1622** [GoldpawsStuff/DiabolicUI#12]
First off, this thing is awesome and I love it! I am setting it up as we speak. 

However, I would love to see a third bar added to be enabled. I think that would be awesome!

Thanks for your hard work.

**Comment by Rusery** [comment]
You can fully supplement with Bartender at least. I can see why Gold did not add a 3rd stacking bar as it would start to make the L/R globes look awkward. If they could add a system that doesn't explicity stack them on top/integrate with the XP bar, that would be mint.

**Comment by Goldpaw** [comment]
Hold ctrl + shift and a few small round buttons with pluses will appear on the side of the globes. Try clicking them. 

All the standard bars are available, though I won't make more than two permanently visible. Remember we're going to get a pet bar and a stance bar too in the upcoming week. I really don't want a five floor tall tower of bars there.
