### ISSUE TITLE
Annoying Grey menu in bottom right corner how do i disable it? ive tried clicking the white plus markers to no avail.

### ISSUE THREAD

**Issue by funnykid201** [GoldpawsStuff/DiabolicUI#31]
https://pasteboard.co/oJC2M3FiB6um.png

the above link is to the picture, and the menu that plagues my ui

**Comment by Sacrilegiusx** [comment]
In the same way I have this problem, when installing the DiabolicUI addon and executing it in version 10.1.5 it shows me that same box which cannot be removed or eliminated

**Comment by maksym-silenko** [comment]
@Goldpaw ya, have the same issue as guys above... It requires hotfix pal.
><img width="1920" alt="image" src="https://github.com/GoldpawsStuff/DiabolicUI/assets/7979478/b1807701-e8f3-4453-b1c0-c16b5df36b1d">

**Details**
- Not a conflict between SexyMap or any other addon I have installed (manually checked with only DiabolicUI enabled)
- Not a conflict between main (DiabolicUI) and your "sub" (clean map, chat blabla) addons (again, checked)
- DiabolicUI 2.0.79-RC
- World of Warcraft 10.2.0.52106

**Comment by Goldpaw** [comment]
No, it actually doesn't. Diabolic hasn't been updated for a very long time, and it's not compatible with any current version. If you uncheck the box to "load out of date addons" in the addon settings, it won't even load. 

This is not a bug, this is a case of somebody using an outdated addon version on the current version of WoW.

DiabolicUI will return, but this is not a bug, and a hotfix won't do anything.
